# Generated by Django 5.2.1 on 2025-06-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Título do Acervo"),
                ),
                ("author", models.CharField(max_length=50, verbose_name="Autor")),
                ("publisher", models.CharField(max_length=30, verbose_name="Editora")),
                ("year_pub", models.IntegerField(verbose_name="Ano")),
            ],
        ),
    ]
