# Generated by Django 5.2.4 on 2025-07-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="id",
        ),
        migrations.AddField(
            model_name="collection",
            name="collection_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID do Acervo"
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="collection_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Livro"),
                    (1, "Notebook"),
                    (2, "Chromebook"),
                    (3, "Tablet"),
                ],
                default=0,
                verbose_name="Tipo de Acervo",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="responsible_person",
            field=models.CharField(
                default="Robson", max_length=100, verbose_name="Pessoa Responsável"
            ),
            preserve_default=False,
        ),
    ]
