# Generated by Django 5.2.4 on 2025-07-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0002_remove_collection_id_collection_collection_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="title",
            new_name="name",
        ),
    ]
