# Generated by Django 5.2.4 on 2025-07-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0003_rename_title_collection_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="collection_id",
            field=models.CharField(
                primary_key=True, serialize=False, verbose_name="ID do Acervo"
            ),
        ),
    ]
