# Generated by Django 5.2.4 on 2025-07-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0004_alter_collection_collection_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={
                "ordering": ["collection_type", "name"],
                "verbose_name": "Acervo",
                "verbose_name_plural": "Acervos",
            },
        ),
    ]
