# Generated by Django 5.2.4 on 2025-07-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0005_alter_collection_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="author",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="year_pub",
        ),
    ]
