# Generated by Django 5.2.4 on 2025-07-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "collection",
            "0006_remove_collection_author_remove_collection_publisher_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Collection",
        ),
    ]
