# Generated by Django 5.2.4 on 2025-07-18 20:05

# import collection_item.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DelayPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_user",
                    models.SmallIntegerField(
                        choices=[(0, "Leitor"), (1, "Funcionário")],
                        verbose_name="Tipo de Usuário",
                    ),
                ),
                (
                    "type_item",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Livro"),
                            (1, "Notebook"),
                            (2, "Chromebook"),
                            (3, "Tablet"),
                        ],
                        verbose_name="Tipo de Item",
                    ),
                ),
                (
                    "max_days",
                    models.PositiveIntegerField(
                        verbose_name="Prazo maximo de emprestimo"
                    ),
                ),
                (
                    "fine_value",
                    models.FloatField(verbose_name="Valor da multa por dias de atraso"),
                ),
                (
                    "delay_tolerance",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tolerância de atraso"
                    ),
                ),
                (
                    "item_limits",
                    models.PositiveIntegerField(
                        verbose_name="Limite de itens simultâneos"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Título da Obra"),
                ),
                (
                    "author",
                    models.CharField(max_length=50, verbose_name="Autor da Obra"),
                ),
                (
                    "publisher",
                    models.CharField(max_length=50, verbose_name="Editora da Obra"),
                ),
                ("year_pub", models.IntegerField(verbose_name="Ano de Publicação")),
            ],
            options={
                "verbose_name": "Obra",
                "verbose_name_plural": "Obras",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id_code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        # validators=[collection_item.validators.id_code_validator],
                        verbose_name="Código Identificador",
                    ),
                ),
                (
                    "preservation",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Novo"),
                            (1, "Bom"),
                            (2, "Regular"),
                            (3, "Ruim"),
                            (4, "Danificado"),
                        ],
                        default=0,
                        verbose_name="Estado de Conservação",
                    ),
                ),
                (
                    "availability",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Disponível"),
                            (1, "Emprestado"),
                            (2, "Reservado"),
                            (3, "Inativo"),
                        ],
                        default=0,
                        verbose_name="Disponibilidade",
                    ),
                ),
                ("entry_date", models.DateField(auto_now_add=True)),
                (
                    "id_work",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="collection_item.work",
                        verbose_name="Obra Associada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Acervo",
                "verbose_name_plural": "Itens do Acervo",
            },
        ),
    ]
