# Generated by Django 5.2.1 on 2025-05-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Título da Obra"),
                ),
                (
                    "id_code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código Identificador",
                    ),
                ),
                (
                    "preservation",
                    models.CharField(
                        choices=[
                            ("Bom", "Bom"),
                            ("Regular", "Regular"),
                            ("Ruim", "Ruim"),
                            ("Danificado", "Danificado"),
                        ],
                        max_length=10,
                        verbose_name="Estado de Consevação",
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("Disponível", "Disponível"),
                            ("Emprestado", "Emprestado"),
                            ("Reservado", "Reservado"),
                            ("Danificado", "Danificado"),
                        ],
                        max_length=10,
                        verbose_name="Disponibilidade",
                    ),
                ),
                ("entry_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
