# Generated by Django 5.2.1 on 2025-05-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_item", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Título da Obra"),
        ),
    ]
