# Generated by Django 5.2.1 on 2025-05-28 23:36

import collection_item.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_item", "0002_alter_collectionitem_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectionitem",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="id_code",
            field=models.CharField(
                max_length=10,
                primary_key=True,
                serialize=False,
                validators=[collection_item.validators.id_code_validator],
                verbose_name="Código Identificador",
            ),
        ),
    ]
