# Generated by Django 5.2.4 on 2025-07-19 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_item", "0002_rename_collectionitem_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Livro"),
                            (1, "Notebook"),
                            (2, "Chromebook"),
                            (3, "Tablet"),
                        ],
                        default=0,
                        verbose_name="Tipo de Acervo",
                    ),
                ),
                (
                    "preservation",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Novo"),
                            (1, "Bom"),
                            (2, "Regular"),
                            (3, "Ruim"),
                            (4, "Danificado"),
                        ],
                        default=0,
                        verbose_name="Estado de Conservação",
                    ),
                ),
                (
                    "availability",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Disponível"),
                            (1, "Emprestado"),
                            (2, "Reservado"),
                            (3, "Inativo"),
                        ],
                        default=0,
                        verbose_name="Disponibilidade",
                    ),
                ),
                ("entry_date", models.DateField(auto_now_add=True)),
                (
                    "responsible_person",
                    models.CharField(max_length=100, verbose_name="Pessoa Responsável"),
                ),
            ],
            options={
                "verbose_name": "Item do Acervo",
                "verbose_name_plural": "Itens do Acervo",
            },
        ),
        migrations.RemoveField(
            model_name="book",
            name="id_work",
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["title"],
                "verbose_name": "Livro",
                "verbose_name_plural": "Livros",
            },
        ),
        migrations.RemoveField(
            model_name="book",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="book",
            name="entry_date",
        ),
        migrations.RemoveField(
            model_name="book",
            name="id_code",
        ),
        migrations.RemoveField(
            model_name="book",
            name="preservation",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(
                default="Jesus", max_length=50, verbose_name="Autor da Obra"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.PositiveSmallIntegerField(
                default=1234567890, verbose_name="ISBN"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(
                default="Deus", max_length=50, verbose_name="Editora da Obra"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="title",
            field=models.CharField(
                default="Cristo", max_length=100, verbose_name="Título da Obra"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="year_pub",
            field=models.IntegerField(default=0, verbose_name="Ano de Publicação"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "collectionitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="collection_item.collectionitem",
                    ),
                ),
                (
                    "brand",
                    models.CharField(max_length=100, verbose_name="Marca/Modelo"),
                ),
                (
                    "specifications",
                    models.TextField(
                        blank=True, null=True, verbose_name="Especificações"
                    ),
                ),
            ],
            bases=("collection_item.collectionitem",),
        ),
        migrations.AddField(
            model_name="book",
            name="collectionitem_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=123,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="collection_item.collectionitem",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Work",
        ),
    ]
