# Generated by Django 5.2.1 on 2025-05-28 23:39

import collection_item.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_item", "0003_alter_collectionitem_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Colletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.CharField(
                        max_length=50,
                        validators=[collection_item.validators.validate_name],
                        verbose_name="Nome do Alterador",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collection_item.collectionitem",
                    ),
                ),
            ],
        ),
    ]
