# Generated by Django 5.2.4 on 2025-07-19 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_item", "0003_collectionitem_remove_book_id_work_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectionitem",
            name="entry_date",
        ),
        migrations.AddField(
            model_name="equipment",
            name="serial_number",
            field=models.CharField(
                default=None,
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="Número de Série",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="collectionitem_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="collection_item.collectionitem",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                max_length=13, primary_key=True, serialize=False, verbose_name="ISBN"
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="collectionitem_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="collection_item.collectionitem",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="specifications",
            field=models.TextField(verbose_name="Especificações"),
        ),
    ]
