# Generated by Django 5.2.4 on 2025-07-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_item", "0004_remove_collectionitem_entry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="responsible_person",
            field=models.CharField(
                help_text="Aqui vai ficar o nome da pessoa responsável pelo Acervo (Bibliotecário por padrão)",
                max_length=100,
                verbose_name="Pessoa Responsável",
            ),
        ),
    ]
