# Generated by Django 5.2.1 on 2025-05-29 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_item", "0004_colletion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectionitem",
            options={
                "ordering": ["title"],
                "verbose_name": "Item do Acervo",
                "verbose_name_plural": "Itens do Acervo",
            },
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="preservation",
            field=models.CharField(
                choices=[
                    ("Bom", "Bom"),
                    ("Regular", "Regular"),
                    ("Ruim", "Ruim"),
                    ("Danificado", "Danificado"),
                ],
                max_length=10,
                verbose_name="Estado de Conservação",
            ),
        ),
        migrations.CreateModel(
            name="ItemStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(max_length=10, verbose_name="Status Anterior"),
                ),
                (
                    "new_status",
                    models.CharField(max_length=10, verbose_name="Novo Status"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Alteração"
                    ),
                ),
                (
                    "changed_by",
                    models.CharField(
                        max_length=100, verbose_name="Responsável pela Alteração"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="collection_item.collectionitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alteração de Status",
                "verbose_name_plural": "Alterações de Status",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.DeleteModel(
            name="Colletion",
        ),
    ]
