# Generated by Django 5.2.4 on 2025-07-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_item", "0005_alter_collectionitem_responsible_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectionitem",
            name="responsible_person",
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                help_text="Digite apenas números",
                max_length=13,
                primary_key=True,
                serialize=False,
                verbose_name="ISBN",
            ),
        ),
    ]
