# Generated by Django 5.2.1 on 2025-05-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_item", "0005_alter_collectionitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="availability",
            field=models.CharField(
                choices=[
                    ("Disponível", "Disponível"),
                    ("Emprestado", "Emprestado"),
                    ("Reservado", "Reservado"),
                ],
                max_length=10,
                verbose_name="Disponibilidade",
            ),
        ),
    ]
