# Generated by Django 5.2.4 on 2025-07-19 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_item", "0006_remove_collectionitem_responsible_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="collectionitem_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="collection_item.collectionitem",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                help_text="Digite apenas números", max_length=13, verbose_name="ISBN"
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="collectionitem_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="collection_item.collectionitem",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="serial_number",
            field=models.CharField(max_length=20, verbose_name="Número de Série"),
        ),
    ]
