# Generated by Django 5.2.1 on 2025-06-02 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_item", "0006_alter_collectionitem_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemstatuschange",
            name="changed_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data da Alteração"
            ),
        ),
    ]
