# Generated by Django 5.2.3 on 2025-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_item", "0007_alter_itemstatuschange_changed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DelayPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_days",
                    models.PositiveIntegerField(
                        verbose_name="Prazo maximo de emprestimo"
                    ),
                ),
                (
                    "fine_value",
                    models.FloatField(verbose_name="Valor da multa por dias de atraso"),
                ),
                (
                    "delay_tolerance",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tolerância de atraso"
                    ),
                ),
                (
                    "item_limits",
                    models.PositiveIntegerField(
                        verbose_name="Limite de itens simultâneos"
                    ),
                ),
            ],
        ),
    ]
