# Generated by Django 5.2.4 on 2025-07-19 22:03

import validadores.validar_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collection_item",
            "0007_alter_book_collectionitem_ptr_alter_book_isbn_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                help_text="Digite apenas números",
                max_length=13,
                validators=[validadores.validar_info.validate_isbn],
                verbose_name="ISBN",
            ),
        ),
    ]
