# Generated by Django 5.2.4 on 2025-07-20 17:33

import django.core.validators
import validadores.validar_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_item", "0008_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectionitem",
            options={
                "ordering": ["type"],
                "verbose_name": "Item do Acervo",
                "verbose_name_plural": "Itens do Acervo",
            },
        ),
        migrations.AlterModelOptions(
            name="delaypolicy",
            options={
                "ordering": ["type_user", "type_item"],
                "verbose_name": "Política de Multa e Atrazo",
                "verbose_name_plural": "Políticas de Multas e Atrazos",
            },
        ),
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "ordering": ["brand", "serial_number"],
                "verbose_name": "Equipamento Digital",
                "verbose_name_plural": "Equipamentos Digitais",
            },
        ),
        migrations.AlterField(
            model_name="delaypolicy",
            name="delay_tolerance",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tempo máximo (em dias) que o usuário pode permanecer com o item sem ser multado.",
                null=True,
                verbose_name="Tolerância de atraso (Opcional)",
            ),
        ),
        migrations.AlterField(
            model_name="delaypolicy",
            name="fine_value",
            field=models.FloatField(
                help_text="O valor da multa é calculado com base no número de dias em que o item não foi devolvido, multiplicado pelo valor diário da multa.",
                validators=[
                    validadores.validar_info.validate_fine_value,
                    django.core.validators.DecimalValidator(5, 2),
                ],
                verbose_name="Valor da multa (por dias)",
            ),
        ),
        migrations.AlterField(
            model_name="delaypolicy",
            name="item_limits",
            field=models.PositiveIntegerField(
                help_text="Limite de Itens que o usuário pode emprestar",
                verbose_name="Limite de itens simultâneos",
            ),
        ),
        migrations.AlterField(
            model_name="delaypolicy",
            name="max_days",
            field=models.PositiveIntegerField(
                help_text="Tempo máximo (em dias) que o usuário poderá permanecer com o Item antes de começar a receber a multa.",
                verbose_name="Prazo maximo de emprestimo (em dias)",
            ),
        ),
        migrations.AlterField(
            model_name="delaypolicy",
            name="type_item",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Livro"),
                    (1, "Notebook"),
                    (2, "Chromebook"),
                    (3, "Tablet"),
                ],
                verbose_name="Tipo de Item",
            ),
        ),
        migrations.AlterField(
            model_name="delaypolicy",
            name="type_user",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Leitor"), (1, "Funcionário")],
                verbose_name="Tipo de Usuário",
            ),
        ),
    ]
