# Generated by Django 5.1.6 on 2025-07-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_item", "0008_delaypolicy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemstatuschange",
            name="changed_by",
            field=models.CharField(
                max_length=150, verbose_name="Responsável pela Alteração"
            ),
        ),
    ]
