# Generated by Django 5.2.4 on 2025-07-20 18:17

import validadores.validar_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection_item", "0009_alter_collectionitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delaypolicy",
            name="fine_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="O valor da multa é calculado com base no número de dias em que o item não foi devolvido, multiplicado pelo valor diário da multa.",
                max_digits=10,
                validators=[validadores.validar_info.validate_fine_value],
                verbose_name="Valor da multa (por dias)",
            ),
        ),
    ]
