# Generated by Django 5.2.1 on 2025-05-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome Completo"),
                ),
                ("cpf", models.IntegerField(max_length=11, verbose_name="CPF")),
                ("cgm", models.IntegerField(max_length=10, verbose_name="CGM")),
                ("email", models.EmailField(max_length=200, verbose_name="E-mail")),
                (
                    "phone",
                    models.PositiveIntegerField(max_length=11, verbose_name="Telefone"),
                ),
            ],
        ),
    ]
