# Generated by Django 5.2.1 on 2025-05-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_reader", "0003_alter_user_cgm_alter_user_cpf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.PositiveIntegerField(
                primary_key=True, serialize=False, verbose_name="CPF"
            ),
        ),
    ]
