# Generated by Django 5.2.1 on 2025-05-19 19:51

import django.core.validators
import user_reader.validar_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_reader", "0004_remove_user_id_alter_user_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cgm",
            field=models.PositiveIntegerField(unique=True, verbose_name="CGM"),
        ),
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                help_text="Formato: 000.000.000-00",
                max_length=14,
                primary_key=True,
                serialize=False,
                validators=[user_reader.validar_info.validate_cpf],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=200,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="E-mail",
            ),
        ),
    ]
