# Generated by Django 5.2.1 on 2025-05-19 19:55

import user_reader.validar_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_reader", "0005_alter_user_cgm_alter_user_cpf_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.PositiveIntegerField(
                help_text="Formato: 000.000.000-00",
                max_length=14,
                primary_key=True,
                serialize=False,
                validators=[user_reader.validar_info.validate_cpf],
                verbose_name="CPF",
            ),
        ),
    ]
