# Generated by Django 5.2.1 on 2025-05-19 23:43

import django.core.validators
import user_reader.validar_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_reader", "0008_alter_user_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cgm",
            field=models.CharField(
                help_text="Código Geral de Matrícula (10 dígitos)",
                max_length=10,
                unique=True,
                validators=[user_reader.validar_info.validate_cgm],
                verbose_name="CGM",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Use o @gmail ou o @escola",
                max_length=200,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                help_text="Esse nome ficará no banco de dados da Secretaria de Educação do Paraná",
                max_length=100,
                verbose_name="Nome Completo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                help_text='\nDigite o número com DDD. Formatos aceitos:\n- Celular: (XX) 9XXXX-XXXX ou XX9XXXXXXXX\n- Fixo: (XX) XXXX-XXXX ou XXXXXXXX\nO "9" inicial é obrigatório para celulares\n',
                max_length=15,
                validators=[user_reader.validar_info.validate_phone],
                verbose_name="Telefone",
            ),
        ),
    ]
