# Generated by Django 5.2.1 on 2025-05-24 19:31

import django.core.validators
import user_reader.validar_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_reader",
            "0009_alter_user_cgm_alter_user_email_alter_user_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="12345678",
                help_text="Coloque uma senha com no mínimo 8 caracteres",
                max_length=100,
                validators=[user_reader.validar_info.validate_password],
                verbose_name="Senha",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                help_text="Não use pontos nem traços",
                max_length=11,
                primary_key=True,
                serialize=False,
                validators=[user_reader.validar_info.validate_cpf],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Use o @gmail ou o @escola",
                max_length=200,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                help_text="Esse nome ficará no banco de dados da Secretaria de Educação do Paraná",
                max_length=100,
                unique=True,
                validators=[user_reader.validar_info.validate_name],
                verbose_name="Nome Completo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                help_text="Digite apenas números, sem pontuações ou espaços. Exemplo: Para (21) 99999-8888, digite 21999998888",
                max_length=11,
                validators=[user_reader.validar_info.validate_phone],
                verbose_name="Telefone",
            ),
        ),
    ]
