# Generated by Django 5.2.1 on 2025-05-25 19:54

import user_reader.validar_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_reader", "0011_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                help_text="Coloque uma senha com no mínimo 8 caracteres",
                max_length=128,
                validators=[user_reader.validar_info.validate_password],
                verbose_name="Senha",
            ),
        ),
    ]
