# Generated by Django 5.2.1 on 2025-05-26 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reader', '0012_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Use o @gmail ou o @escola', max_length=50, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
    ]
