# Generated by Django 5.2.3 on 2025-06-23 12:06

import user.validar_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Esse nome ficará no banco de dados da Secretaria de Educação do Paraná', max_length=150, unique=True, validators=[user.validar_info.validate_name], verbose_name='Nome'),
        ),
    ]
