# Generated by Django 5.1.6 on 2025-06-30 22:02

import django.core.validators
import validadores.validar_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                help_text="Digite seu número de celular ou telefone fixo, adicione também seu DDD.",
                max_length=11,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    validadores.validar_info.validate_phone,
                ],
                verbose_name="Telefone",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Digite seu nome e sobrenome com letra maiúscula no começo",
                max_length=150,
                unique=True,
                validators=[validadores.validar_info.validate_name],
                verbose_name="Nome Completo",
            ),
        ),
    ]
