# Generated by Django 5.2.1 on 2025-05-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cgm",
            field=models.IntegerField(verbose_name="CGM"),
        ),
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.IntegerField(verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.PositiveIntegerField(verbose_name="Telefone"),
        ),
    ]
