# Generated by Django 5.2.1 on 2025-05-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_cgm_alter_user_cpf_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cgm",
            field=models.PositiveIntegerField(verbose_name="CGM"),
        ),
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.PositiveIntegerField(verbose_name="CPF"),
        ),
    ]
