# Generated by Django 5.1.6 on 2025-07-06 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modifier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Ativo"), (1, "Bloqueado"), (2, "Suspenso")],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="UserChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_date", models.DateTimeField(auto_now_add=True)),
                ("field_changed", models.CharField(max_length=50)),
                ("old_value", models.TextField()),
                ("new_value", models.TextField()),
                ("change_type", models.CharField(max_length=20)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Alteração",
                "verbose_name_plural": "Registros de Alteração",
                "ordering": ["-change_date"],
            },
        ),
    ]
