# Generated by Django 5.2.4 on 2025-07-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_last_modified_by_user_status_userchangelog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["type_user", "username"],
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
    ]
