# Generated by Django 5.2.1 on 2025-05-19 22:13

import user.validar_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.IntegerField(
                help_text="Formato: 000.000.000-00",
                max_length=14,
                primary_key=True,
                serialize=False,
                validators=[user.validar_info.validate_cpf],
                verbose_name="CPF",
            ),
        ),
    ]
