# Generated by Django 5.1.6 on 2025-06-16 22:22

import user.validar_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type_user",
            field=models.CharField(
                choices=[
                    ("LEITOR", "Leitor"),
                    ("FUNCIONARIO", "Funcionário"),
                    ("BIBLIOTECARIO", "Bibliotecario"),
                ],
                default="Leitor",
                help_text="Escolha o tipo de usuário",
                max_length=13,
                verbose_name="Tipo de Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="cgm",
            field=models.CharField(
                blank=True,
                help_text="Código Geral de Matrícula (10 dígitos)",
                max_length=10,
                unique=True,
                validators=[user.validar_info.validate_cgm],
                verbose_name="CGM",
            ),
        ),
    ]
