# Generated by Django 5.1.6 on 2025-06-17 00:41

import user.validar_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_user_type_user_alter_user_cgm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cgm",
            field=models.CharField(
                blank=True,
                help_text="Código Geral de Matrícula (10 dígitos)",
                max_length=10,
                null=True,
                unique=True,
                validators=[user.validar_info.validate_cgm],
                verbose_name="CGM",
            ),
        ),
    ]
