# Generated by Django 5.2.1 on 2025-06-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_cgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Leitor'), (1, 'Funcionário'), (2, 'Bibliotecario')], default=0, help_text='Escolha o tipo de usuário', verbose_name='Tipo de Usuário'),
        ),
    ]
