# Generated by Django 5.1.6 on 2025-06-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_alter_user_type_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type_user",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Leitor"), (1, "Funcionário"), (2, "Bibliotecário")],
                default=0,
                help_text="Escolha o tipo de usuário",
                verbose_name="Tipo de Usuário",
            ),
        ),
    ]
